"""Import legacy LUNA TinyURL mappings into ``luna_route``.

The usual source is ``data/tinyurls.txt``, a pasted MariaDB result set. The
importer also accepts the CSV generated by ``scripts/get_data.py``.
"""

import argparse
import csv
import re
from pathlib import Path

import bootstrap
from project_paths import DATA_DIR
from sqlalchemy import create_engine, text


TABLE_ROW_RE = re.compile(
    r"^\|\s*(?P<token>[^|]+?)\s*\|\s*(?P<target_url>https?://.*?)\s*\|\s*$"
)


def classify_tinyurl(target_url):
    if "/luna/servlet/widget/detail/" in target_url:
        return "widget_detail"
    if "/luna/servlet/detail/" in target_url:
        return "detail"
    if "/luna/servlet/workspace" in target_url:
        return "workspace"
    if "/luna/servlet/view/search" in target_url:
        return "search"
    if "/luna/servlet/view/all" in target_url or "/luna/servlet/widget/view/all" in target_url:
        return "browse"
    if "/luna/servlet/s/" in target_url:
        return "shortlink"
    if "/MediaManager/" in target_url:
        return "media_manager"
    if "/ll/thumbnailView.html" in target_url:
        return "thumbnail_view"
    if "/luna/servlet/" in target_url:
        return "luna_other"
    return "other"


def read_mariadb_table_dump(path):
    """Yield token, route type and URL from a MariaDB CLI table result."""
    with path.open(encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            match = TABLE_ROW_RE.match(line)
            if not match:
                continue
            token = match.group("token").strip()
            target_url = match.group("target_url").rstrip()
            if token and target_url:
                yield token, classify_tinyurl(target_url), target_url, line_number


def read_csv_routes(path):
    with path.open(newline="", encoding="utf-8-sig") as handle:
        for line_number, row in enumerate(csv.DictReader(handle), start=2):
            token = (row.get("token") or "").strip()
            route_type = (row.get("route_type") or "").strip()
            target_url = (row.get("target_url") or "").strip()
            if token and route_type and target_url:
                yield token, route_type, target_url, line_number


def read_routes(path):
    if path.suffix.lower() == ".csv":
        yield from read_csv_routes(path)
    else:
        yield from read_mariadb_table_dump(path)


def main():
    parser = argparse.ArgumentParser(description="Import legacy LUNA TinyURL routes.")
    parser.add_argument(
        "source",
        nargs="?",
        type=Path,
        default=DATA_DIR / "tinyurls.txt",
        help="MariaDB table dump (.txt) or generated route CSV (default: data/tinyurls.txt)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Validate and report without writing.")
    args = parser.parse_args()

    if not args.source.is_file():
        parser.error(f"Source file does not exist: {args.source}")

    # The database has a unique token key. A dump may include an earlier
    # duplicate token, so let its last appearance win and report that fact.
    routes = {}
    duplicate_tokens = 0
    for token, route_type, target_url, line_number in read_routes(args.source):
        if len(token) > 64 or len(route_type) > 64 or len(target_url) > 2048:
            raise ValueError(
                f"Invalid route at {args.source}:{line_number}: token/type/URL exceeds table limits"
            )
        if token in routes:
            duplicate_tokens += 1
        routes[token] = (route_type, target_url)

    if not routes:
        raise ValueError(f"No TinyURL mappings found in {args.source}")

    if args.dry_run:
        print(
            f"Validated {len(routes)} unique routes from {args.source} "
            f"({duplicate_tokens} duplicate token row(s), last value retained)."
        )
        return

    # This deliberately uses SQLAlchemy directly rather than importing the
    # Flask application, allowing migration jobs to run independently of the
    # web service process.
    from config import SQLALCHEMY_DATABASE_URI

    engine = create_engine(SQLALCHEMY_DATABASE_URI)
    select_route = text(
        "SELECT route_type, target_url FROM luna_route WHERE token = :token"
    )
    insert_route = text(
        "INSERT INTO luna_route (token, route_type, target_url) "
        "VALUES (:token, :route_type, :target_url)"
    )
    update_route = text(
        "UPDATE luna_route SET route_type = :route_type, target_url = :target_url "
        "WHERE token = :token"
    )

    created = updated = unchanged = 0
    with engine.begin() as connection:
        for token, (route_type, target_url) in routes.items():
            parameters = {
                "token": token,
                "route_type": route_type,
                "target_url": target_url,
            }
            existing = connection.execute(select_route, {"token": token}).fetchone()
            if not existing:
                connection.execute(insert_route, parameters)
                created += 1
            elif existing[0] != route_type or existing[1] != target_url:
                connection.execute(update_route, parameters)
                updated += 1
            else:
                unchanged += 1

    print(
        f"LUNA route import complete from {args.source}. "
        f"Created: {created}, Updated: {updated}, Unchanged: {unchanged}, "
        f"Duplicate source tokens: {duplicate_tokens}"
    )


if __name__ == "__main__":
    main()
